name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # можно 3.11, если требуется

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Show Python and pip versions
        run: |
          python --version
          pip --version

      # Run PyInstaller to create single-file exe
      - name: Build EXE with PyInstaller
        run: |
          # Указываем имя скрипта и встраиваем папку templates (Windows uses ';' separator)
          pyinstaller --clean --onefile --name auto_macro --add-data "templates;templates" auto_macro.py

      - name: List dist dir
        run: dir dist

      - name: Upload artifact (exe)
        uses: actions/upload-artifact@v4
        with:
          name: auto_macro-exe
          path: dist/auto_macro.exe
